on:
  push:
    branches:
      - "master"
  pull_request:

name: "Build"

jobs:
  build-docker:
    name: "Build Docker image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Build Docker image"
        run: |
          docker build .
